### ISSUE TITLE
Racc::ParseError

### ISSUE THREAD

**Issue by taf2** [cxn03651/writeexcel#42]
parse error on value ":" (error)
from /usr/local/lib/ruby/2.1.0/racc/parser.rb:529:in `on_error'
from /usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
from /usr/local/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'

on a line of code like:
worksheet.write(row_index, col_index, col_value.to_s)

where col_value is a String similar to

word   :  word :  word\nword  : ....

**Comment by cxn03651** [comment]
thank you for using writeexcel gem.

> worksheet.write(row_index, col_index, col_value.to_s)

can you send me col_value.to_s which causes exception, please.


cxn03651

**Comment by taf2** [comment]
I did find a work around using write_string instead of write.  In the meantime, I can share the content but it needs to be over a private channel.

**Comment by cxn03651** [comment]
Worksheet#write calls write_formula when string matches /^=/.  write_formula call parse_formula to parse string as formula. If string is not excel formula, racc causes error.  It is recommended for you to use write_string if you want to store string.
